version: '3'

services:
  app:
    image: "mcr.microsoft.com/devcontainers/javascript-node:20"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      SHELL: /bin/zsh

  chroma:
    image: "chromadb/chroma:latest"
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat" ]
      interval: 30s
      timeout: 10s
      retries: 3
